files: src/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.8
    hooks:
      - id: pylint
        name: pylint-py
        args:
          # Disable specific checks that are handled by Black
          - "--disable=C0301,R0801,W0201"
          # Set custom rules for variable and attribute names
          - "--variable-rgx=[a-z_][a-z0-9_]{1,30}$"
          - "--attr-rgx=[a-zA-Z_][a-zA-Z0-9_]{1,30}$"
          - "--argument-rgx=[a-z_][a-z0-9_]{1,30}$"
          # Exclude specific packages from certain checks
          - "--generated-members=torch.*,pandas.*,Levenshtein.*"
          # Set limits for code complexity
          - "--max-locals=25"
          - "--max-attributes=20"
